# Site settings
title: datanaut
email: christopher.r.zhou@gmail.com
description: Exploring, discovering and "charting" the Dataverse
url: ""
username: chrisrzhou
include: ["_templates"]

category: [visualizations, tutorials, other, site]


# Build settings
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]  # to add id to headers

permalink: /posts/:categories/:year/:month/:day/:title
