# Site settings
title: bigdatalib.io
email: nima.safaian@gmail.com
description: Data Science Journey into Energy, Trading and Risk Management
url: ""
username: bigdatalib
include: ["_pages"]

category: [visualizations, tutorials, other, site, tags, archive]
collections:
  about:
    output: false
  blog:
    output: true
  projects:
    output: true
  resume:
    output: false

# Build settings
timezone: America/Denver
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]  # to add id to headers

permalink: /blog/:categories/:year/:month/:day/:title
