# Site settings
title: Datanaut
email: christopher.r.zhou@gmail.com
description: Exploring, discovering and "charting" Dataspace
url: ""
username: chrisrzhou
category: [projects, tutorials, influences, art, site]
collections: [resume, projects]
include: ["_pages"]



# Build settings
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]  # to add id to headers
