# Site settings
title: datanaut
email: christopher.r.zhou@gmail.com
description: Exploring, discovering and "charting" the Dataverse
url: ""
username: chrisrzhou
include: ["_templates"]

category: [visualizations, tutorials, other, site, tags, archive]
collections:
  - projects
  - resume

# Build settings
timezone: America/Houston
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]  # to add id to headers

permalink: /posts/:categories/:year/:month/:day/:title
