# Site settings
title: datanaut
email: christopher.r.zhou@gmail.com
description: Exploring, discovering and "charting" the Dataverse
url: ""
username: chrisrzhou
include: ["_pages"]
image-logo: https://s3-us-west-1.amazonaws.com/chrisrzhou/datanaut/site/images/ink/spaceship.png
image-frame: https://s3-us-west-1.amazonaws.com/chrisrzhou/datanaut/site/images/ink/motherboard.png
image-about: https://s3-us-west-1.amazonaws.com/chrisrzhou/datanaut/site/images/ink/datanaut.png
image-blog: https://s3-us-west-1.amazonaws.com/chrisrzhou/datanaut/site/images/ink/wireframe.png
image-projects: https://s3-us-west-1.amazonaws.com/chrisrzhou/datanaut/site/images/ink/datacubes.png
image-resume: https://s3-us-west-1.amazonaws.com/chrisrzhou/datanaut/site/images/ink/spaceship2.png

category: [visualizations, tutorials, other, site, tags, archive]
collections:
  about:
    output: false
  blog:
    output: true
  projects:
    output: true
  resume:
    output: false

# Build settings
timezone: America/Houston
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]  # to add id to headers

permalink: /blog/:categories/:year/:month/:day/:title
